spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/CustomersDB
    username: username
    password: password
  flyway:
    url: jdbc:postgresql://localhost:5432/CustomersDB
    username: username
    password: password
    enabled: true


